import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from 'next/font/google';
import "./globals.css";
import Navbar from "./components/nav";
import FooterBar from "./components/footer";

const geistSans = localFont({
  src: "./fonts/Inter.ttf",
  variable: "--font-inter",
  weight: "100 900",
});

const Inter_init = Inter({
  subsets: ['latin'],
  weight: ['300'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={Inter_init.variable}
      >
        <Navbar />
        {children}
        <FooterBar />
      </body>
    </html> 
  );
}
